### ISSUE TITLE
deps

### ISSUE THREAD

**Issue by gedw99** [FollowTheProcess/spok#173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hey @FollowTheProcess 

I am very impressed with the way the io streams and globbing works BTW. it's really expandable to anything. 

I have tons of repos and out of them come go binaries and these binaries are used in other repos.  

Makefiles check if the binary is in a location called .deps and what version it is. This allows the Makefile to call the binary, and if its not there, the Make file ( called base.mk)  will just get the binary and the version, and then the call then is allowed through to run against the binary. This is all currently Makefiles.

Each Repo has a single Makefile that declares the binaries and versions it needs. Each Binary has a Makefile that gets pulled into the .deps folder, so that the binaries can be acted on use Make to call them.

Its really system based on make to allow compete control of any binaries dependencies or any sort. It works for ffmpeg, golang, whatever.

I think that because Spok is so similar to Make, that it might be possible. Its just that I rely on include files to make it work, because each repo that produces a binary also has a .mk that goes along with the binary, allowing other projects that use Make to reuse the logic in the .mk file. SO this leads me to ask if Spok has any option of "includes" like what Make has.

**Comment by FollowTheProcess** [comment]
> I am very impressed with the way the io streams and globbing works BTW. it's really expandable to anything.

Thankyou! :)

There's currently no concept of "includes" no, I've not been actively working on the project for a while and have actually been contemplating a bit of a rewrite, I wrote this first a while ago and think it needs a bit of a refresh so including other spokfiles might become part of that, I have a number of other ideas too

Just a question of finding the time!
