### ISSUE TITLE
is else Or similar

### ISSUE THREAD

**Issue by gedw99** [FollowTheProcess/spok#176]
How can we do if else, or similar or should we avoid it ?

I could not really see an example to do this in the Spokfile.

Use case..

I also do a which to see if a binary is installed and what version it is.  If it's not the one configured then install.

here is my makefile doing it: https://github.com/gedw99/build-mono/blob/main/Makefile#L192

```make


GH_BIN_NAME=gh
ifeq ($(BASE_GOOS_NAME),windows)
	GH_BIN_NAME=gh.exe
endif
GH_BIN_VERSION=v2.59.0
GH_BIN_WHICH=$(shell $(WHICH_BIN_NAME) $(GH_BIN_NAME))

this-release-dep-del:
	rm -rf $(GH_BIN_WHICH)

this-release-dep: this-dep

ifeq ($(GH_BIN_WHICH), )
	@echo ""
	@echo "$(GH_BIN_NAME) dep check: failed"
	# https://github.com/cli/cli/releases/tag/v2.59.0


	rm -rf $(BASE_DEP_DOWNLOAD_ROOT)
	mkdir -p $(BASE_DEP_DOWNLOAD_ROOT)
	@echo $(BASE_DEP_DOWNLOAD_ROOT_NAME) >> .gitignore


	cd $(BASE_DEP_DOWNLOAD_ROOT) && git clone https://github.com/cli/cli -b v2.59.0
	cd $(BASE_DEP_DOWNLOAD_ROOT) && touch go.work
	cd $(BASE_DEP_DOWNLOAD_ROOT) && go work use cli

	mkdir -p $(BASE_DEP_ROOT)
	cd $(BASE_DEP_DOWNLOAD_ROOT)/cli && go build -o $(BASE_DEP_ROOT)/$(GH_BIN_NAME) ./cmd/gh
	rm -rf $(BASE_DEP_DOWNLOAD_ROOT)
else
	@echo ""
	@echo "$(GH_BIN_NAME) dep check: passed"
	@echo ""
endif

```

**Comment by FollowTheProcess** [comment]
Sadly not no! This is one of the improvements I have in mind to address (either tweak or in a rewrite) when I mentioned in https://github.com/FollowTheProcess/spok/issues/173#issuecomment-2414306596.

However each line in a task body is just a shell script effectively so you could probably do something using the shell `if`

**Comment by FollowTheProcess** [comment]
> It will not work on all OS and ARCH ?

Yep, it should do :) We use a pure Go shell interpreter so it has no system dependencies at all
