### ISSUE TITLE
spot --init throws Error: spokfile already exists

### ISSUE THREAD

**Issue by gedw99** [FollowTheProcess/spok#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### How would this feature be useful?

```sh

spok --init
Error: spokfile already exists at /Users/apple/workspace/go/src/github.com/gedw99/spokfile

```

### Describe the solution you'd like

could we make this idempotent ?

so if a Spokfile / spokfile already exists,  then just ignore it.

**Comment by FollowTheProcess** [comment]
Thanks for the suggestion :) I think I want to keep it like this to be honest, it's in line with what other tools do and I think the least surprising thing to do. For example here is task doing the same thing:

<img width="255" alt="image" src="https://github.com/user-attachments/assets/bd3c5dd8-5b23-475e-97ad-8256d3ff845d">

It would be a bit surprising if it just did nothing when running, we could maybe output a warning but then it's not really a different experience than the error IMO
